export const ADD_ANSWER = "ADD_ANSWER";
export const CHANGE_NEW_ANSWER_PROPERTIES = "CHANGE_NEW_ANSWER_PROPERTIES";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const EDIT_ANSWER = "EDIT_ANSWER";
export const FIND_ANSWERS_BY_QUESTION = "FIND_ANSWERS_BY_QUESTION";
export const LOAD_ANSWERS = "LOAD_ANSWERS";