export const ADD_ANSWER = "ADD_ANSWER";
export const CHANGE_NEW_ANSWER_PROPERTIES = "CHANGE_NEW_ANSWER_PROPERTIES";
export const DELETE_ANSWER = "DELETE_ANSWER";
export const EDIT_ANSWER = "EDIT_ANSWER";
export const UPVOTE_ANSWER = "UPVOTE_ANSWER";
export const DOWNVOTE_ANSWER = "DOWNVOTE_ANSWER";