export const ADD_QUESTION = "ADD_QUESTION";
export const CHANGE_NEW_QUESTION_PROPERTIES = "CHANGE_NEW_QUESTION_PROPERTIES";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const EDIT_QUESTION = "EDIT_QUESTION";
export const SEARCH_QUESTION = "SEARCH_QUESTION";
export const LOAD_QUESTIONS = "LOAD_QUESTIONS";